# Generated by Django 5.2.8 on 2025-11-11 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Problema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("maximizar", "maximizar"),
                            ("minimizar", "minimizar"),
                        ],
                        default="maximizar",
                        max_length=10,
                    ),
                ),
                ("descricao", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Funcao_Objetiva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "coeficiente",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                (
                    "problema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="confeitaria.problema",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="confeitaria.produto",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Restricao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.CharField(max_length=255)),
                ("coeficientes", models.CharField(max_length=255)),
                (
                    "sinal",
                    models.CharField(
                        choices=[("<=", "<="), (">=", ">="), ("=", "=")], max_length=3
                    ),
                ),
                (
                    "limite",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                (
                    "problema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="confeitaria.problema",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Restricao_Coeficiente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("coeficiente", models.DecimalField(decimal_places=4, max_digits=10)),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="confeitaria.produto",
                    ),
                ),
                (
                    "restricao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="confeitaria.restricao",
                    ),
                ),
            ],
        ),
    ]
