# Generated by Django 5.2.8 on 2025-11-11 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("confeitaria", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="restricao",
            name="coeficientes",
        ),
    ]
