# Generated by Django 5.2.8 on 2025-11-11 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("confeitaria", "0002_remove_restricao_coeficientes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="funcao_objetiva",
            name="coeficiente",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="restricao",
            name="limite",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="restricao_coeficiente",
            name="coeficiente",
            field=models.FloatField(default=0),
        ),
    ]
