# Generated by Django 5.2.8 on 2025-11-11 01:41

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("confeitaria", "0003_alter_funcao_objetiva_coeficiente_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="funcao_objetiva",
            name="coeficiente",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="restricao",
            name="limite",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="restricao_coeficiente",
            name="coeficiente",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.CreateModel(
            name="Resultado_Problema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(max_length=50)),
                (
                    "valor_otimo",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("data_calculo", models.DateTimeField(auto_now_add=True)),
                (
                    "problema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="confeitaria.problema",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Resultado_Variavel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="confeitaria.produto",
                    ),
                ),
                (
                    "resultado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variaveis",
                        to="confeitaria.resultado_problema",
                    ),
                ),
            ],
        ),
    ]
